version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - output_data:/app/output
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - HOST=0.0.0.0
      - PATIENT_GENERATOR_THREADS=8
      - PATIENT_GENERATOR_MAX_MEMORY=8192
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/config/defaults"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '4'
          memory: 8G
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    command: >
      uvicorn app:app --host 0.0.0.0 
      --port 8000 
      --workers 8 
      --proxy-headers

  load-balancer:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - web
    restart: always

volumes:
  output_data:
    driver: local
