services:
  cli:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/output
      - ./config:/app/config  # Mount for config files
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PATIENT_GENERATOR_THREADS=4
      - PATIENT_GENERATOR_MAX_MEMORY=4096
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    # Override the default command to run the CLI tool instead of the web server
    command: python run_generator.py --patients 1440 --output /app/output
