services:
  cli:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/output
      - ./config:/app/config  # Mount for config files
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PATIENT_GENERATOR_THREADS=4
      - PATIENT_GENERATOR_MAX_MEMORY=4096
      - REDIS_URL=redis://redis:6379/0
      - CACHE_TTL=${CACHE_TTL:-3600}
      - CACHE_ENABLED=${CACHE_ENABLED:-True}
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    # Override the default command to run the CLI tool instead of the web server
    command: python run_generator.py --patients 1440 --output /app/output

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "unless-stopped"
    command: redis-server --appendonly yes
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  redis_data:
    driver: local
