services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard port (optional, secured with basic auth)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/config:/etc/traefik/config
      - ./traefik/acme:/etc/traefik/acme
    networks:
      - web
    restart: always
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - web
    expose:
      - "8000"  # Only expose to the network, not to the host
    volumes:
      - output_data:/app/output
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - HOST=0.0.0.0
      - PATIENT_GENERATOR_THREADS=4
      - PATIENT_GENERATOR_MAX_MEMORY=4096
      - DATABASE_URL=postgresql://medgen_user:medgen_password@db:5432/medgen_db
      - DB_TYPE=postgres
      - REDIS_URL=redis://redis:6379/0
      - CACHE_TTL=${CACHE_TTL:-3600}
      - CACHE_ENABLED=${CACHE_ENABLED:-True}
      - API_KEY=${API_KEY:-your_secret_api_key_here}
      - DEBUG=${DEBUG:-False}
      - CORS_ORIGINS=${CORS_ORIGINS:-}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    command: >
      uvicorn src.main:app --host 0.0.0.0 
      --port 8000 
      --workers 4 
      --proxy-headers
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.patientgenerator.rule=Host(`patientgenerator.example.com`)"
      - "traefik.http.routers.patientgenerator.entrypoints=websecure"
      - "traefik.http.routers.patientgenerator.tls.certresolver=le"
      - "traefik.http.services.patientgenerator.loadbalancer.server.port=8000"
      # Redirect HTTP to HTTPS
      - "traefik.http.routers.patientgenerator-http.rule=Host(`patientgenerator.example.com`)"
      - "traefik.http.routers.patientgenerator-http.entrypoints=web"
      - "traefik.http.routers.patientgenerator-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=medgen_user
      - POSTGRES_PASSWORD=medgen_password
      - POSTGRES_DB=medgen_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medgen_user -d medgen_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "unless-stopped"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - web
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "unless-stopped"
    command: redis-server --appendonly yes
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  web:
    external: true

volumes:
  output_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
