version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard port (optional, secured with basic auth)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/config:/etc/traefik/config
      - ./traefik/acme:/etc/traefik/acme
    networks:
      - web
    restart: always
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - web
    expose:
      - "8000"  # Only expose to the network, not to the host
    volumes:
      - output_data:/app/output
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - HOST=0.0.0.0
      - PATIENT_GENERATOR_THREADS=4
      - PATIENT_GENERATOR_MAX_MEMORY=4096
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/config/defaults"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    command: >
      uvicorn app:app --host 0.0.0.0 
      --port 8000 
      --workers 4 
      --proxy-headers
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.patientgenerator.rule=Host(`patientgenerator.example.com`)"
      - "traefik.http.routers.patientgenerator.entrypoints=websecure"
      - "traefik.http.routers.patientgenerator.tls.certresolver=le"
      - "traefik.http.services.patientgenerator.loadbalancer.server.port=8000"
      # Redirect HTTP to HTTPS
      - "traefik.http.routers.patientgenerator-http.rule=Host(`patientgenerator.example.com`)"
      - "traefik.http.routers.patientgenerator-http.entrypoints=web"
      - "traefik.http.routers.patientgenerator-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  web:
    external: true

volumes:
  output_data:
    driver: local
