name: medical-patients-generator-redis
region: nyc

services:
  - name: api
    github:
      repo: banton/medical-patients
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: |
      if [ ! -z "$DATABASE_URL" ]; then
        alembic upgrade head
        python scripts/ensure_demo_key.py
      fi
      python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT
    source_dir: /
    environment_slug: python
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    http_port: 8080
    health_check:
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
      http_path: /docs
    envs:
      - key: DATABASE_URL
        value: ${medical-patients-db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
      - key: REDIS_URL
        value: ${REDIS_URL}
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: CACHE_ENABLED
        value: "true"
        scope: RUN_AND_BUILD_TIME
      - key: DEBUG
        value: "false"
        scope: RUN_AND_BUILD_TIME
      - key: CORS_ORIGINS
        value: "https://milmed.tech"
        scope: RUN_AND_BUILD_TIME
      - key: API_KEY
        value: ${API_KEY}
        scope: RUN_AND_BUILD_TIME
        type: SECRET


static_sites:
  - name: frontend
    github:
      repo: banton/medical-patients
      branch: main
      deploy_on_push: true
    source_dir: /static

databases:
  - name: medical-patients-db
    engine: PG
    version: "17"
    production: true

domains:
  - domain: milmed.tech
    type: PRIMARY

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: api
        preserve_path_prefix: true
    
    - match:
        path:
          prefix: /docs
      component:
        name: api
        preserve_path_prefix: true
    
    - match:
        path:
          prefix: /openapi.json
      component:
        name: api
        preserve_path_prefix: true
    
    - match:
        path:
          prefix: /
      component:
        name: frontend