version: '3'

# Medical Patients Generator - Simple Task Runner
# Only includes commands that actually work

env:
  COMPOSE_PROJECT_NAME: medical-patients
  PYTHONPATH: "{{.ROOT_DIR}}"

vars:
  PYTHON:
    sh: which python3 || which python

tasks:
  default:
    desc: Show available tasks
    silent: true
    cmds:
      - echo "Medical Patients Generator - Task Runner"
      - echo "========================================"
      - echo ""
      - echo "Available commands:"
      - echo "  task dev        - Start dev mode (local Python + Docker DB)"
      - echo "  task start      - Start all services in Docker"
      - echo "  task stop       - Stop all services"
      - echo "  task test       - Run all tests"
      - echo "  task clean      - Clean up Docker resources"
      - echo ""
      - echo "Run 'task --list' to see all tasks with descriptions"

  dev:
    desc: Start development environment with logs (database + app)
    cmds:
      - docker compose up -d db redis
      - sleep 5  # Wait for database to be ready
      - "{{.PYTHON}} -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"

  start:
    desc: Start all services in background
    cmds:
      - docker compose up -d --build

  test:
    desc: Run all tests
    cmds:
      - "{{.PYTHON}} -m pytest"

  test-unit:
    desc: Run unit tests only
    cmds:
      - "{{.PYTHON}} -m pytest tests/unit -v"

  test-integration:
    desc: Run integration tests
    cmds:
      - "{{.PYTHON}} -m pytest tests/test_*.py -v --ignore=tests/unit"

  stop:
    desc: Stop all services
    cmds:
      - docker compose down

  clean:
    desc: Clean up Docker resources and Python cache
    cmds:
      - docker compose down -v
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type f -name "*.pyc" -delete 2>/dev/null || true

  db-migrate:
    desc: Run database migrations
    cmds:
      - alembic upgrade head

  db-reset:
    desc: Reset database (WARNING - destroys all data)
    cmds:
      - docker compose down -v
      - docker compose up -d db
      - sleep 5
      - alembic upgrade head

  timeline-viewer:
    desc: Start React timeline viewer
    dir: patient-timeline-viewer
    cmds:
      - npm install
      - npm run dev