# traefik.toml

[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "INFO"

[api]
  dashboard = true
  insecure = false

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false
  
  [providers.file]
    directory = "/etc/traefik/config"
    watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.le.acme]
  email = "your-email@example.com"
  storage = "/etc/traefik/acme/acme.json"
  
  [certificatesResolvers.le.acme.tlsChallenge]
