version: '3'

# Timeline Viewer Module
# Manages React-based patient timeline visualization component

vars:
  TIMELINE_DIR: patient-timeline-viewer
  TIMELINE_PORT: 5174
  NODE_CMD:
    sh: |
      if command -v node >/dev/null 2>&1; then
        echo "node"
      else
        echo "❌ Node.js not found. Please install Node.js from https://nodejs.org/"
        exit 1
      fi
  NPM_CMD:
    sh: |
      if command -v npm >/dev/null 2>&1; then
        echo "npm"
      else
        echo "❌ npm not found. Please install Node.js from https://nodejs.org/"
        exit 1
      fi

tasks:
  # Main development commands
  dev:
    desc: Start React timeline viewer in development mode
    aliases: [viewer, start]
    cmds:
      - echo "🚀 Starting React timeline viewer (port {{.TIMELINE_PORT}})..."
      - task: check-deps
      - echo "📊 Timeline viewer will be available at http://localhost:{{.TIMELINE_PORT}}"
      - cd {{.TIMELINE_DIR}} && {{.NPM_CMD}} run dev

  build:
    desc: Build timeline viewer for production
    cmds:
      - echo "🏗️  Building timeline viewer for production..."
      - task: check-deps
      - task: check-env
      - cd {{.TIMELINE_DIR}} && {{.NPM_CMD}} run build
      - echo "✅ Timeline viewer built successfully"
      - echo "📁 Build output available in {{.TIMELINE_DIR}}/dist/"

  preview:
    desc: Preview production build of timeline viewer
    cmds:
      - echo "👀 Starting timeline viewer preview..."
      - task: build
      - cd {{.TIMELINE_DIR}} && {{.NPM_CMD}} run preview

  # Development and testing
  lint:
    desc: Run ESLint on timeline viewer code
    cmds:
      - echo "🔍 Running ESLint on timeline viewer..."
      - task: check-deps
      - cd {{.TIMELINE_DIR}} && {{.NPM_CMD}} run lint

  test:
    desc: Test timeline viewer (build test)
    cmds:
      - echo "🧪 Testing timeline viewer..."
      - task: check-deps
      - echo "Running build test..."
      - cd {{.TIMELINE_DIR}} && {{.NPM_CMD}} run build
      - echo "✅ Timeline viewer test completed"

  # Dependency management
  install:
    desc: Install timeline viewer dependencies
    aliases: [deps]
    cmds:
      - echo "📦 Installing timeline viewer dependencies..."
      - task: check-env
      - cd {{.TIMELINE_DIR}} && {{.NPM_CMD}} install
      - echo "✅ Timeline viewer dependencies installed"

  update:
    desc: Update timeline viewer dependencies
    cmds:
      - echo "⬆️  Updating timeline viewer dependencies..."
      - task: check-env
      - cd {{.TIMELINE_DIR}} && {{.NPM_CMD}} update
      - echo "✅ Timeline viewer dependencies updated"

  # Cleanup commands
  clean:
    desc: Clean timeline viewer build files and cache
    cmds:
      - echo "🧹 Cleaning timeline viewer build files..."
      - rm -rf {{.TIMELINE_DIR}}/dist 2>/dev/null || true
      - rm -rf {{.TIMELINE_DIR}}/node_modules/.cache 2>/dev/null || true
      - echo "✅ Timeline viewer cleaned"

  clean-deps:
    desc: Remove timeline viewer node_modules and reinstall
    cmds:
      - echo "🧹 Removing timeline viewer dependencies..."
      - rm -rf {{.TIMELINE_DIR}}/node_modules 2>/dev/null || true
      - rm -rf {{.TIMELINE_DIR}}/package-lock.json 2>/dev/null || true
      - echo "📦 Reinstalling timeline viewer dependencies..."
      - task: install

  # Full stack development
  full-dev:
    desc: Start both backend and timeline viewer (parallel)
    cmds:
      - echo "🚀 Starting full development environment..."
      - echo "📊 Backend - http://localhost:8000"
      - echo "📈 Timeline Viewer - http://localhost:{{.TIMELINE_PORT}}"
      - echo "Starting services..."
      - task: :docker:services
      - echo "Starting backend..."
      - task: :development:dev &
      - sleep 3
      - echo "Starting timeline viewer..."
      - task: dev

  # Utility tasks
  check-env:
    desc: Check if timeline viewer environment is ready
    silent: true
    cmds:
      - |
        # Check if timeline directory exists
        if [ ! -d "{{.TIMELINE_DIR}}" ]; then
          echo "❌ Timeline viewer directory not found: {{.TIMELINE_DIR}}"
          exit 1
        fi
        
        # Check if package.json exists
        if [ ! -f "{{.TIMELINE_DIR}}/package.json" ]; then
          echo "❌ Timeline viewer package.json not found"
          exit 1
        fi

  check-deps:
    desc: Check if timeline viewer dependencies are installed
    silent: true
    cmds:
      - task: check-env
      - |
        # Check if node_modules exists
        if [ ! -d "{{.TIMELINE_DIR}}/node_modules" ]; then
          echo "📦 Timeline viewer dependencies not found. Installing..."
          task timeline:install
        fi

  status:
    desc: Show timeline viewer environment status
    cmds:
      - echo "📊 Timeline Viewer Status:"
      - echo "  Directory - {{.TIMELINE_DIR}}"
      - echo "  Port - {{.TIMELINE_PORT}}"
      - |
        if [ -d "{{.TIMELINE_DIR}}" ]; then
          echo "  ✅ Directory exists"
        else
          echo "  ❌ Directory missing"
        fi
      - |
        if [ -f "{{.TIMELINE_DIR}}/package.json" ]; then
          echo "  ✅ Package.json found"
        else
          echo "  ❌ Package.json missing"
        fi
      - |
        if [ -d "{{.TIMELINE_DIR}}/node_modules" ]; then
          echo "  ✅ Dependencies installed"
        else
          echo "  ❌ Dependencies missing"
        fi
      - |
        if [ -d "{{.TIMELINE_DIR}}/dist" ]; then
          echo "  ✅ Production build exists"
        else
          echo "  ⚠️  No production build"
        fi

  info:
    desc: Display timeline viewer project information
    cmds:
      - echo "📈 Patient Timeline Viewer"
      - echo ""
      - echo "🔧 Technology Stack:"
      - echo "  • React 18 with TypeScript"
      - echo "  • Vite build system"
      - echo "  • Tailwind CSS styling"
      - echo "  • Framer Motion animations"
      - echo ""
      - echo "📁 Project Structure:"
      - echo "  • {{.TIMELINE_DIR}}/src/components/ - React components"
      - echo "  • {{.TIMELINE_DIR}}/src/types/ - TypeScript definitions"
      - echo "  • {{.TIMELINE_DIR}}/src/utils/ - Timeline engine logic"
      - echo "  • {{.TIMELINE_DIR}}/public/ - Static assets"
      - echo ""
      - echo "🌐 Available Commands:"
      - echo "  • task timeline:dev - Start development server"
      - echo "  • task timeline:build - Build for production"
      - echo "  • task timeline:preview - Preview production build"
      - echo "  • task timeline:full-dev - Start backend + timeline"