"""add_version_and_parent_to_config_templates

Revision ID: 2b84a220e9ac
Revises: 88eedb601203
Create Date: 2025-05-16 17:12:43.772730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b84a220e9ac'
down_revision: Union[str, None] = '3cf60fdf0504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration_templates', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('configuration_templates', sa.Column('parent_config_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'configuration_templates', 'configuration_templates', ['parent_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'configuration_templates', type_='foreignkey')
    op.drop_column('configuration_templates', 'parent_config_id')
    op.drop_column('configuration_templates', 'version')
    # ### end Alembic commands ###
