"""add patient timeline tracking table

Revision ID: 491f84d4f7ce
Revises: 2b84a220e9ac
Create Date: 2025-06-11 08:48:36.273428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "491f84d4f7ce"
down_revision: Union[str, None] = "2b84a220e9ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("demographics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("medical_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("treatment_history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("current_status", sa.String(), nullable=False),
        sa.Column("day_of_injury", sa.String(), nullable=True),
        sa.Column("injury_type", sa.String(), nullable=True),
        sa.Column("triage_category", sa.String(), nullable=True),
        sa.Column("nationality", sa.String(), nullable=True),
        sa.Column("front", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("primary_condition", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("primary_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("additional_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_facility", sa.String(), nullable=True),
        sa.Column("final_status", sa.String(), nullable=True),
        sa.Column("movement_timeline", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("injury_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_duration_hours", sa.Float(), nullable=True),
        sa.Column("facilities_visited", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_events", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("job_id", "patient_id"),
    )
    op.create_index(op.f("ix_patients_job_id"), "patients", ["job_id"], unique=False)
    op.create_index(op.f("ix_patients_patient_id"), "patients", ["patient_id"], unique=False)
    op.create_foreign_key(None, "configuration_templates", "configuration_templates", ["parent_config_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "configuration_templates", type_="foreignkey")
    op.drop_index(op.f("ix_patients_patient_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_job_id"), table_name="patients")
    op.drop_table("patients")
    # ### end Alembic commands ###
