"""create_initial_tables_for_configs_and_jobs

Revision ID: 88eedb601203
Revises: 3cf60fdf0504
Create Date: 2025-05-16 16:51:39.055637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88eedb601203'
down_revision: Union[str, None] = '3cf60fdf0504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('front_configs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('facility_configs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('injury_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_patients', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_templates_id'), 'configuration_templates', ['id'], unique=False)
    op.create_index(op.f('ix_configuration_templates_name'), 'configuration_templates', ['name'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('progress_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_size', sa.Integer(), nullable=True),
    sa.Column('total_size_formatted', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_configuration_templates_name'), table_name='configuration_templates')
    op.drop_index(op.f('ix_configuration_templates_id'), table_name='configuration_templates')
    op.drop_table('configuration_templates')
    # ### end Alembic commands ###
